### ISSUE TITLE
3-arrow-functions.js - tried all gist examples.

### ISSUE THREAD

**Issue by sectortwofive** [andrewjmead/node-course-v3-code#6]
Tried all examples on gist, they all produce the same error.

console.log(tasks.getTasksToDo())
                  ^

TypeError: tasks.getTasksToDo is not a function
    at Object.<anonymous> (/home/nemi/code/playground/3-arrow-functions.js:16:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
[nodemon] app crashed - waiting for file changes before starting...

**Comment by thazhemadam** [comment]
> This happened to me many times because of circular dependency, check if you have 2 classes that are requiring each other, remove one of them from requiring the other and the issue should be solved [1]

Check if this solves your issue.

_References: [[1]](https://stackoverflow.com/questions/33865068/typeerror-is-not-a-function-in-node-js)_
